<?php

///////////////////////////////////////////////////////////////////////
//
//  This file is to catalog all the SQL queries ran within the website 
//  and reference them in a unified location.  Any issues or reasoning 
//  for not referencing are listed below.
//
//////////////////////////////////////////////////////////////////////


// These are the team scores and specialist scores group by team and by specialist
	$score_team = "SELECT  `Team Assignment`, 
					IF((ROUND(AVG(antivirus),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(antivirus),1),'</font>'),IF((ROUND(AVG(antivirus),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(antivirus),1),'</font>'),ROUND(AVG(antivirus),1))) AS 'Antivirus',
					IF((ROUND(AVG(DISK),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(DISK),1),'</font>'),IF((ROUND(AVG(DISK),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(DISK),1),'</font>'),ROUND(AVG(DISK),1))) AS 'Disk',
					IF((ROUND(AVG(intrusion),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(intrusion),1),'</font>'),IF((ROUND(AVG(intrusion),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(intrusion),1),'</font>'),ROUND(AVG(intrusion),1))) AS 'Intrusion',
					IF((ROUND(AVG(usability),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(usability),1),'</font>'),IF((ROUND(AVG(usability),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(usability),1),'</font>'),ROUND(AVG(usability),1))) AS 'Usability',
					IF((ROUND(AVG(services),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(services),1),'</font>'),IF((ROUND(AVG(services),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(services),1),'</font>'),ROUND(AVG(services),1))) AS 'Services',
					IF((ROUND(AVG(updates),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(updates),1),'</font>'),IF((ROUND(AVG(updates),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(updates),1),'</font>'),ROUND(AVG(updates),1))) AS 'Updates',
					IF((ROUND(AVG(`Event Log`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Event Log`),1),'</font>'),IF((ROUND(AVG(`Event Log`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Event Log`),1),'</font>'),ROUND(AVG(`Event Log`),1))) AS 'Events',
					IF((ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1),'</font>'),IF((ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1),'</font>'),ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1))) AS 'Overall Score'
					FROM hc_scores GROUP BY `Team Assignment`";
	$score_team_ex = "SELECT hc_scores.`Team Assignment`,
					IF((ROUND(AVG(`AV Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`AV Ex`),1),'</font>'),IF((ROUND(AVG(`AV Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`AV Ex`),1),'</font>'),ROUND(AVG(`AV Ex`),1))) AS 'Antivirus',
					IF((ROUND(AVG(`Disk Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Disk Ex`),1),'</font>'),IF((ROUND(AVG(`Disk Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Disk Ex`),1),'</font>'),ROUND(AVG(`Disk Ex`),1))) AS 'Disk',
					IF((ROUND(AVG(`Intrusion Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Intrusion Ex`),1),'</font>'),IF((ROUND(AVG(`Intrusion Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Intrusion Ex`),1),'</font>'),ROUND(AVG(`Intrusion Ex`),1))) AS 'Intrusion',
					IF((ROUND(AVG(`Usability Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Usability Ex`),1),'</font>'),IF((ROUND(AVG(`Usability Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Usability Ex`),1),'</font>'),ROUND(AVG(`Usability Ex`),1))) AS 'Usability',
					IF((ROUND(AVG(`Services Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Services Ex`),1),'</font>'),IF((ROUND(AVG(`Services Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Services Ex`),1),'</font>'),ROUND(AVG(`Services Ex`),1))) AS 'Services',
					IF((ROUND(AVG(`Updates Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Updates Ex`),1),'</font>'),IF((ROUND(AVG(`Updates Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Updates Ex`),1),'</font>'),ROUND(AVG(`Updates Ex`),1))) AS 'Updates',
					IF((ROUND(AVG(`Event Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Event Ex`),1),'</font>'),IF((ROUND(AVG(`Event Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Event Ex`),1),'</font>'),ROUND(AVG(`Event Ex`),1))) AS 'Events',
					IF((ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1),'</font>'),IF((ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1),'</font>'),ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1))) AS 'Overall Score'
					FROM hc_scores JOIN v_extradataclients USING (clientid) WHERE v_extradataclients.`Exclude Reporting` <> 1  AND clientid NOT IN(SELECT clientid FROM `v_extradataclients` WHERE `v_extradataclients`.`Go Live Date` < DATE_ADD(NOW(), INTERVAL -1 MONTH) AND `v_extradataclients`.`Go Live Date` > 0) GROUP BY hc_scores.`Team Assignment`";
	$score_spec_ex = "SELECT `Client Specialist`,
					IF((ROUND(AVG(`AV Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`AV Ex`),1),'</font>'),IF((ROUND(AVG(`AV Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`AV Ex`),1),'</font>'),ROUND(AVG(`AV Ex`),1))) AS 'Antivirus',
					IF((ROUND(AVG(`Disk Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Disk Ex`),1),'</font>'),IF((ROUND(AVG(`Disk Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Disk Ex`),1),'</font>'),ROUND(AVG(`Disk Ex`),1))) AS 'Disk',
					IF((ROUND(AVG(`Intrusion Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Intrusion Ex`),1),'</font>'),IF((ROUND(AVG(`Intrusion Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Intrusion Ex`),1),'</font>'),ROUND(AVG(`Intrusion Ex`),1))) AS 'Intrusion',
					IF((ROUND(AVG(`Usability Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Usability Ex`),1),'</font>'),IF((ROUND(AVG(`Usability Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Usability Ex`),1),'</font>'),ROUND(AVG(`Usability Ex`),1))) AS 'Usability',
					IF((ROUND(AVG(`Services Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Services Ex`),1),'</font>'),IF((ROUND(AVG(`Services Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Services Ex`),1),'</font>'),ROUND(AVG(`Services Ex`),1))) AS 'Services',
					IF((ROUND(AVG(`Updates Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Updates Ex`),1),'</font>'),IF((ROUND(AVG(`Updates Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Updates Ex`),1),'</font>'),ROUND(AVG(`Updates Ex`),1))) AS 'Updates',
					IF((ROUND(AVG(`Event Ex`),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Event Ex`),1),'</font>'),IF((ROUND(AVG(`Event Ex`),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Event Ex`),1),'</font>'),ROUND(AVG(`Event Ex`),1))) AS 'Events',
					IF((ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1) < 75), CONCAT('<img src=images/red-warning-shield-16.png> <font color=red>',ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1),'</font>'),IF((ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1) < 90), CONCAT('<img src=images/warning-shield-16.png> <font color=black>',ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1),'</font>'),ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1))) AS 'Overall Score'
					FROM hc_scores JOIN v_extradataclients USING (clientid) WHERE `Client Specialist` != 'None' GROUP BY `Client Specialist`";

// These are the trending page queries.  Not currently called by anything due to the order and sort in the query				
	$trend_updates = "SELECT IF((computers.lastcontact > date_add(now(),interval -10 minute)), '<img src=../images/online.png>','<img src=../images/offline.png>') as 'Status', computerid, computers.name as 'Computer Name', eventdate as 'Event Date', SUBSTRING(stat20,7) as 'Updates Details' FROM h_extrastatsdaily JOIN computers USING (computerid) WHERE computers.computerid={$computerid} AND INSTR(stat20,\";^\") AND eventdate > DATE_ADD(NOW(), INTERVAL -1 MONTH) ORDER BY {$field} {$sort}";				
	$trend_services = "SELECT IF((computers.lastcontact > date_add(now(),interval -10 minute)), '<img src=../images/online.png>','<img src=../images/offline.png>') AS 'Status', computerid, computers.name as 'Computer Name', eventdate as 'Event Date', SUBSTRING(stat19,6) as 'Services Details' FROM h_extrastatsdaily JOIN computers USING (computerid) WHERE computers.computerid={$computerid} AND INSTR(stat19,\";\") AND eventdate > DATE_ADD(NOW(), INTERVAL -1 MONTH) ORDER BY {$field} {$sort}";				
	$trend_intrusion = "SELECT IF((computers.lastcontact > date_add(now(),interval -10 minute)), '<img src=../images/online.png>','<img src=../images/offline.png>') AS 'Status', computerid, computers.name as 'Computer Name', eventdate as 'Event Date', SUBSTRING(stat17,6) as 'Intrusion Details' FROM h_extrastatsdaily JOIN computers USING (computerid) WHERE computers.computerid={$computerid} AND stat17 < 1 AND eventdate > DATE_ADD(NOW(), INTERVAL -1 MONTH) ORDER BY {$field} {$sort}";
	$trend_events = "SELECT IF((computers.lastcontact > date_add(now(),interval -10 minute)), '<img src=../images/online.png>','<img src=../images/offline.png>') AS 'Status', computerid, computers.name as 'Computer Name', eventdate as 'Event Date', SUBSTRING(stat14,6) as 'Events Details' FROM h_extrastatsdaily JOIN computers USING (computerid) WHERE computers.computerid={$computerid} AND INSTR(stat14,\";\") AND event14 <> -1 AND eventdate > DATE_ADD(NOW(), INTERVAL -1 MONTH) ORDER BY {$field} {$sort}";
	$trend_disk = "SELECT IF((computers.lastcontact > date_add(now(),interval -10 minute)), '<img src=../images/online.png>','<img src=../images/offline.png>') AS 'Status', computerid, computers.name as 'Computer Name', eventdate as 'Event Date', SUBSTRING(stat16,6) as 'Disk Details' FROM h_extrastatsdaily JOIN computers USING (computerid) WHERE computers.computerid={$computerid} AND (INSTR(stat16,\";|\") OR INSTR(stat16,\";\[\")) AND eventdate > DATE_ADD(NOW(), INTERVAL -1 MONTH) ORDER BY {$field} {$sort}";
	$trend_antivirus = "SELECT IF((computers.lastcontact > date_add(now(),interval -10 minute)), '<img src=../images/online.png>','<img src=../images/offline.png>') AS 'Status', computerid, computers.name as 'Computer Name', eventdate as 'Event Date', SUBSTRING(stat15,8) as 'Antivirus Details' FROM h_extrastatsdaily JOIN computers USING (computerid) WHERE computers.computerid={$computerid} AND INSTR(stat15,\";.,\") AND eventdate > DATE_ADD(NOW(), INTERVAL -1 MONTH) ORDER BY {$field} {$sort}";
	$trend_usability = "SELECT IF((computers.lastcontact > date_add(now(),interval -10 minute)), '<img src=../images/online.png>','<img src=../images/offline.png>') AS 'Status', computerid, computers.name as 'Computer Name', eventdate as 'Event Date', SUBSTRING(stat18,7) as 'Usability Details' FROM h_extrastatsdaily JOIN computers USING (computerid) WHERE computers.computerid={$computerid} AND (INSTR(stat18,\";^\") OR INSTR(stat18,\";:\")) AND eventdate > DATE_ADD(NOW(), INTERVAL -1 MONTH) ORDER BY {$field} {$sort}";

//  These are the client specialist queries to pull the teams groups by the specialist.  Not currently called by anything due to the order and sort variables in the query.
	$spec_client = "SELECT	`Client Name`,
					IF((ROUND(AVG(`AV Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`AV Ex`),1),'</font>'),IF((ROUND(AVG(`AV Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`AV Ex`),1),'</font>'),ROUND(AVG(`AV Ex`),1))) AS 'Antivirus',
					IF((ROUND(AVG(`Disk Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Disk Ex`),1),'</font>'),IF((ROUND(AVG(`Disk Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Disk Ex`),1),'</font>'),ROUND(AVG(`Disk Ex`),1))) AS 'Disk',
					IF((ROUND(AVG(`Intrusion Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Intrusion Ex`),1),'</font>'),IF((ROUND(AVG(`Intrusion Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Intrusion Ex`),1),'</font>'),ROUND(AVG(`Intrusion Ex`),1))) AS 'Intrusion',
					IF((ROUND(AVG(`Usability Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Usability Ex`),1),'</font>'),IF((ROUND(AVG(`Usability Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Usability Ex`),1),'</font>'),ROUND(AVG(`Usability Ex`),1))) AS 'Usability',
					IF((ROUND(AVG(`Services Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Services Ex`),1),'</font>'),IF((ROUND(AVG(`Services Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Services Ex`),1),'</font>'),ROUND(AVG(`Services Ex`),1))) AS 'Services',
					IF((ROUND(AVG(`Updates Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Updates Ex`),1),'</font>'),IF((ROUND(AVG(`Updates Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Updates Ex`),1),'</font>'),ROUND(AVG(`Updates Ex`),1))) AS 'Updates',
					IF((ROUND(AVG(`Event Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Event Ex`),1),'</font>'),IF((ROUND(AVG(`Event Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Event Ex`),1),'</font>'),ROUND(AVG(`Event Ex`),1))) AS 'Events',
					IF((ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1),'</font>'),IF((ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1),'</font>'),ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1))) AS 'Overall Score'
					FROM hc_scores JOIN v_extradataclients USING (clientid) WHERE v_extradataclients.`Exclude Reporting` <> 1 AND `Client Specialist` = '{$net_sp}' GROUP BY `Client Name` ORDER BY {$field} {$sort}";

	$spec_client_ex = "SELECT `Client Name`, 
					IF((ROUND(AVG(`Antivirus`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Antivirus`),1),'</font>'),IF((ROUND(AVG(`Antivirus`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Antivirus`),1),'</font>'),ROUND(AVG(`Antivirus`),1))) AS 'Antivirus',
					IF((ROUND(AVG(`Disk`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Disk`),1),'</font>'),IF((ROUND(AVG(`Disk`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Disk`),1),'</font>'),ROUND(AVG(`Disk`),1))) AS 'Disk',
					IF((ROUND(AVG(`Intrusion`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Intrusion`),1),'</font>'),IF((ROUND(AVG(`Intrusion`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Intrusion`),1),'</font>'),ROUND(AVG(`Intrusion`),1))) AS 'Intrusion',
					IF((ROUND(AVG(`Usability`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Usability`),1),'</font>'),IF((ROUND(AVG(`Usability`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Usability`),1),'</font>'),ROUND(AVG(`Usability`),1))) AS 'Usability',
					IF((ROUND(AVG(`Services`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Services`),1),'</font>'),IF((ROUND(AVG(`Services`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Services`),1),'</font>'),ROUND(AVG(`Services`),1))) AS 'Services',
					IF((ROUND(AVG(`Updates`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Updates`),1),'</font>'),IF((ROUND(AVG(`Updates`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Updates`),1),'</font>'),ROUND(AVG(`Updates`),1))) AS 'Updates',
					IF((ROUND(AVG(`Event Log`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Event Log`),1),'</font>'),IF((ROUND(AVG(`Event Log`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Event Log`),1),'</font>'),ROUND(AVG(`Event Log`),1))) AS 'Events',
					IF((ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1),'</font>'),IF((ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1),'</font>'),ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1))) AS 'Overall Score'
					FROM hc_scores JOIN v_extradataclients USING (clientid) WHERE `Client Specialist` = '{$net_sp}' GROUP BY `Client Name` ORDER BY {$field} {$sort}";

// These are the team scores grouped by clients.  Not currently called by anything due to the order and sort variables in the query.
	$score_client = "SELECT `Client Name`,
					IF((ROUND(AVG(`AV Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`AV Ex`),1),'</font>'),IF((ROUND(AVG(`AV Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`AV Ex`),1),'</font>'),ROUND(AVG(`AV Ex`),1))) AS 'Antivirus',
					IF((ROUND(AVG(`Disk Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Disk Ex`),1),'</font>'),IF((ROUND(AVG(`Disk Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Disk Ex`),1),'</font>'),ROUND(AVG(`Disk Ex`),1))) AS 'Disk',
					IF((ROUND(AVG(`Intrusion Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Intrusion Ex`),1),'</font>'),IF((ROUND(AVG(`Intrusion Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Intrusion Ex`),1),'</font>'),ROUND(AVG(`Intrusion Ex`),1))) AS 'Intrusion',
					IF((ROUND(AVG(`Usability Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Usability Ex`),1),'</font>'),IF((ROUND(AVG(`Usability Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Usability Ex`),1),'</font>'),ROUND(AVG(`Usability Ex`),1))) AS 'Usability',
					IF((ROUND(AVG(`Services Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Services Ex`),1),'</font>'),IF((ROUND(AVG(`Services Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Services Ex`),1),'</font>'),ROUND(AVG(`Services Ex`),1))) AS 'Services',
					IF((ROUND(AVG(`Updates Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Updates Ex`),1),'</font>'),IF((ROUND(AVG(`Updates Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Updates Ex`),1),'</font>'),ROUND(AVG(`Updates Ex`),1))) AS 'Updates',
					IF((ROUND(AVG(`Event Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Event Ex`),1),'</font>'),IF((ROUND(AVG(`Event Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Event Ex`),1),'</font>'),ROUND(AVG(`Event Ex`),1))) AS 'Events',
					IF((ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1),'</font>'),IF((ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1),'</font>'),ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1))) AS 'Overall Score'
					FROM hc_scores JOIN v_extradataclients USING (clientid) WHERE v_extradataclients.`Exclude Reporting` <> 1 AND hc_scores.clientid NOT IN(SELECT clientid FROM `v_extradataclients` WHERE `v_extradataclients`.`Go Live Date` < DATE_ADD(NOW(), INTERVAL -1 MONTH) AND `v_extradataclients`.`Go Live Date` > 0) AND hc_scores.`Team Assignment` = '{$careteam}' GROUP BY `Client Name` ORDER BY {$field} {$sort}";
			
	$score_client_ex = "SELECT `Client Name`, 
						IF((ROUND(AVG(`Antivirus`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Antivirus`),1),'</font>'),IF((ROUND(AVG(`Antivirus`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Antivirus`),1),'</font>'),ROUND(AVG(`Antivirus`),1))) AS 'Antivirus',
						IF((ROUND(AVG(`Disk`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Disk`),1),'</font>'),IF((ROUND(AVG(`Disk`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Disk`),1),'</font>'),ROUND(AVG(`Disk`),1))) AS 'Disk',
						IF((ROUND(AVG(`Intrusion`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Intrusion`),1),'</font>'),IF((ROUND(AVG(`Intrusion`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Intrusion`),1),'</font>'),ROUND(AVG(`Intrusion`),1))) AS 'Intrusion',
						IF((ROUND(AVG(`Usability`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Usability`),1),'</font>'),IF((ROUND(AVG(`Usability`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Usability`),1),'</font>'),ROUND(AVG(`Usability`),1))) AS 'Usability',
						IF((ROUND(AVG(`Services`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Services`),1),'</font>'),IF((ROUND(AVG(`Services`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Services`),1),'</font>'),ROUND(AVG(`Services`),1))) AS 'Services',
						IF((ROUND(AVG(`Updates`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Updates`),1),'</font>'),IF((ROUND(AVG(`Updates`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Updates`),1),'</font>'),ROUND(AVG(`Updates`),1))) AS 'Updates',
						IF((ROUND(AVG(`Event Log`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Event Log`),1),'</font>'),IF((ROUND(AVG(`Event Log`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Event Log`),1),'</font>'),ROUND(AVG(`Event Log`),1))) AS 'Events',
						IF((ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1),'</font>'),IF((ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1),'</font>'),ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1))) AS 'Overall Score'
						FROM hc_scores WHERE hc_scores.`Team Assignment` = '{$careteam}' GROUP BY `Client Name` ORDER BY {$field} {$sort}";

// These are the client scores grouped by computers.  Not currently called by anything due to the order and sort variables in the query.
	$score_comp = "SELECT computerid, `Computer Name`,IF((computers.lastcontact > date_add(now(),interval -10 minute)), '<img src=../images/online.png>','<img src=../images/offline.png>') AS 'Status',
					IF((os LIKE '%server%'), 'srv', IF((os LIKE '%darwin%'), 'mac', IF((os LIKE '%linux%'), 'linux', 'winwork'))) AS 'os',
					IF((ROUND(AVG(`AV Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`AV Ex`),1),'</font>'),IF((ROUND(AVG(`AV Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`AV Ex`),1),'</font>'),ROUND(AVG(`AV Ex`),1))) AS 'Antivirus',
					IF((ROUND(AVG(`Disk Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Disk Ex`),1),'</font>'),IF((ROUND(AVG(`Disk Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Disk Ex`),1),'</font>'),ROUND(AVG(`Disk Ex`),1))) AS 'Disk',
					IF((ROUND(AVG(`Intrusion Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Intrusion Ex`),1),'</font>'),IF((ROUND(AVG(`Intrusion Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Intrusion Ex`),1),'</font>'),ROUND(AVG(`Intrusion Ex`),1))) AS 'Intrusion',
					IF((ROUND(AVG(`Usability Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Usability Ex`),1),'</font>'),IF((ROUND(AVG(`Usability Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Usability Ex`),1),'</font>'),ROUND(AVG(`Usability Ex`),1))) AS 'Usability',
					IF((ROUND(AVG(`Services Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Services Ex`),1),'</font>'),IF((ROUND(AVG(`Services Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Services Ex`),1),'</font>'),ROUND(AVG(`Services Ex`),1))) AS 'Services',
					IF((ROUND(AVG(`Updates Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Updates Ex`),1),'</font>'),IF((ROUND(AVG(`Updates Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Updates Ex`),1),'</font>'),ROUND(AVG(`Updates Ex`),1))) AS 'Updates',
					IF((ROUND(AVG(`Event Ex`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Event Ex`),1),'</font>'),IF((ROUND(AVG(`Event Ex`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Event Ex`),1),'</font>'),ROUND(AVG(`Event Ex`),1))) AS 'Events',
					IF((ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1),'</font>'),IF((ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1),'</font>'),ROUND(((ROUND(AVG(`AV Ex`),1)+ROUND(AVG(`Disk Ex`),1)+ROUND(AVG(`Intrusion Ex`),1)+ROUND(AVG(`Usability Ex`),1)+ROUND(AVG(`Services Ex`),1)+ROUND(AVG(`Updates Ex`),1)+ROUND(AVG(`Event Ex`),1))/7),1))) AS 'Overall Score'
					FROM hc_scores_computers JOIN v_extradataclients USING (clientid) left join computers using (computerid) WHERE v_extradataclients.`Exclude Reporting` <> 1 AND `Client Name` = '{$client}' GROUP BY `Computerid` ORDER BY {$field} {$sort}";

	$score_comp_ex = "SELECT computerid, `Computer Name`,IF((computers.lastcontact > date_add(now(),interval -10 minute)), '<img src=../images/online.png>','<img src=../images/offline.png>') AS 'Status', 
					IF((os LIKE '%server%'), 'srv', IF((os LIKE '%darwin%'), 'mac', IF((os LIKE '%linux%'), 'linux', 'winwork'))) AS 'os',
					IF((ROUND(AVG(`Antivirus`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Antivirus`),1),'</font>'),IF((ROUND(AVG(`Antivirus`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Antivirus`),1),'</font>'),ROUND(AVG(`Antivirus`),1))) AS 'Antivirus',
					IF((ROUND(AVG(`Disk`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Disk`),1),'</font>'),IF((ROUND(AVG(`Disk`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Disk`),1),'</font>'),ROUND(AVG(`Disk`),1))) AS 'Disk',
					IF((ROUND(AVG(`Intrusion`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Intrusion`),1),'</font>'),IF((ROUND(AVG(`Intrusion`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Intrusion`),1),'</font>'),ROUND(AVG(`Intrusion`),1))) AS 'Intrusion',
					IF((ROUND(AVG(`Usability`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Usability`),1),'</font>'),IF((ROUND(AVG(`Usability`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Usability`),1),'</font>'),ROUND(AVG(`Usability`),1))) AS 'Usability',
					IF((ROUND(AVG(`Services`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Services`),1),'</font>'),IF((ROUND(AVG(`Services`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Services`),1),'</font>'),ROUND(AVG(`Services`),1))) AS 'Services',
					IF((ROUND(AVG(`Updates`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Updates`),1),'</font>'),IF((ROUND(AVG(`Updates`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Updates`),1),'</font>'),ROUND(AVG(`Updates`),1))) AS 'Updates',
					IF((ROUND(AVG(`Event Log`),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(AVG(`Event Log`),1),'</font>'),IF((ROUND(AVG(`Event Log`),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(AVG(`Event Log`),1),'</font>'),ROUND(AVG(`Event Log`),1))) AS 'Events',
					IF((ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1) < 75), CONCAT('<img src=../images/red-warning-shield-16.png> <font color=red>',ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1),'</font>'),IF((ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1) < 90), CONCAT('<img src=../images/warning-shield-16.png> <font color=black>',ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1),'</font>'),ROUND(((ROUND(AVG(`Antivirus`),1)+ROUND(AVG(`Disk`),1)+ROUND(AVG(`Intrusion`),1)+ROUND(AVG(`Usability`),1)+ROUND(AVG(`Services`),1)+ROUND(AVG(`Updates`),1)+ROUND(AVG(`Event Log`),1))/7),1))) AS 'Overall Score'
					FROM hc_scores_computers JOIN v_extradataclients USING (clientid) left join computers using (computerid) WHERE `Client Name` = '{$client}' GROUP BY `Computerid` ORDER BY {$field} {$sort}";
			
// These are the exclusion queries.
	$exclude_comp = "SELECT `client name`, `team assignment`, `computer name`,
					IF(`Ignore Antivirus`=1,'<img src=../images/check.png>','') 'Ignore Antivirus',
					IF(`Ignore Disk`=1,'<img src=../images/check.png>','') 'Ignore Disk',
					IF(`Ignore Intrusion`=1,'<img src=../images/check.png>','') 'Ignore Intrusion',
					IF(`Ignore Usability`=1,'<img src=../images/check.png>','') 'Ignore Usability',
					IF(`Ignore Services`=1,'<img src=../images/check.png>','') 'Ignore Services',
					IF(`Ignore Updates`=1,'<img src=../images/check.png>','') 'Ignore Updates',
					IF(`Ignore Event Logs`=1,'<img src=../images/check.png>','') 'Ignore Events',
					`Exclusion Comments`
					 FROM marco_hc_computer_exclusion";
	$exclude_client = "SELECT clientid, `Client Name`,`Team Assignment`,
					if((`Exclude Reporting`=1),'<img src=../images/check.png>','') 'Exclude Reporting',
					IF(`Ignore Antivirus`=1,'<img src=../images/check.png>','') 'Ignore Antivirus',
					IF(`Ignore Disk`=1,'<img src=../images/check.png>','') 'Ignore Disk',
					IF(`Ignore Intrusion`=1,'<img src=../images/check.png>','') 'Ignore Intrusion',
					IF(`Ignore Usability`=1,'<img src=../images/check.png>','') 'Ignore Usability',
					IF(`Ignore Services`=1,'<img src=../images/check.png>','') 'Ignore Services',
					IF(`Ignore Updates`=1,'<img src=../images/check.png>','') 'Ignore Updates',
					IF(`Ignore Event Log`=1,'<img src=../images/check.png>','') 'Ignore Event Log',
					`Go Live Date`,`Exclusion Comments` 
					FROM `marco_hc_client_exclusions`";

// These are the navigation list population queries.
	$list_spec = "SELECT distinct `Client Specialist` as netsp FROM v_extradataclients WHERE `Client Specialist` != 'None' order by netsp asc";
	$list_team = "SELECT distinct `Team Assignment` as netsp FROM hc_scores";				 

?>













